FROM icr.io/appcafe/websphere-liberty:kernel-java8-openj9-ubi

ARG VERBOSE=false
ARG FEATURE_REPO_URL=""
# ENV OPENJ9_SCC=false

COPY --chown=1001:0  src/main/liberty/config/server.xml /config/
COPY --chown=1001:0  target/greeting.war /config/apps/

RUN date && configure.sh && date
