FROM icr.io/appcafe/open-liberty:kernel-slim-java8-openj9-ubi

ARG VERBOSE=false
# ENV OPENJ9_SCC=false

COPY --chown=1001:0  src/main/liberty/config/server.xml /config/
RUN features.sh

COPY --chown=1001:0  target/greeting.war /config/apps/
RUN configure.sh
