apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- greeting.ConfigMap.yaml
- greeting.wlapp.yaml
# labels:
# - includeSelectors: true
#   pairs:
#     app: greeting-xyz
# nameSuffix: -xyz
patches:
- path: applicationImage.Patch.yaml
# - patch: |-
#     - op: replace
#       path: /spec/env/0/valueFrom/configMapKeyRef/name
#       value: greeting-xyz
#   target:
#     kind: WebSphereLibertyApplication
- patch: |-
    - op: replace
      path: /data/greetings
      value: Hello from WebSphere Liberty managed by WebSphere Liberty Operator;Hello from the pipeline
  target:
    kind: ConfigMap