apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- greeting.ConfigMap.yaml
- greeting.wlapp.yaml
commonLabels:
  app: greeting-cicd
nameSuffix: -cicd
patches:
  - patch: |-
      - op: replace
        path: /spec/env/0/valueFrom/configMapKeyRef/name
        value: greeting-cicd
    target:
      kind: WebSphereLibertyApplication
  - patch: |-
      - op: replace
        path: /data/greetings
        value: Hello from WebSphere Liberty managed by WebSphere Liberty Operator;Hello from CI/CD pipeline
    target:
      kind: ConfigMap
patchesStrategicMerge:
- applicationImage.Patch.yaml